spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qr_code
    username: root
    password: 123456
  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


